### ISSUE TITLE
batch correction

### ISSUE THREAD

**Issue by JBreunig** [bendemeo/shannonca#2]
I think that I'm getting reduce_scanpy to work correctly but when I try to run correct_scanpy, I get the following:

> sca.correct_scanpy(adata, batch_key='batch', n_features=1000)
computing PCA
    with n_comps=50
    finished (0:00:02)
computing PCA
    with n_comps=50
    finished (0:00:01)

> Traceback (most recent call last):
> 
>   File "<ipython-input-9-67a377b6bdfe>", line 1, in <module>
>     sca.correct_scanpy(adata, batch_key='batch', n_features=1000)
> 
>   File "/home/[user]/anaconda3/lib/python3.8/site-packages/shannonca/integrate.py", line 34, in correct_scanpy
>     gene_sigs = np.array(np.mean(np.abs(abatch.layers['scalpel_score'].todense()), axis=0)).flatten()
> 
>   File "/home/[user]/anaconda3/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
>     return self._data[key]
> 
> KeyError: 'scalpel_score'

Thanks in advance for the help!

**Comment by bendemeo** [comment]
Thank you for the comment, and I apologize for my long-delayed response. The functions in the `integrate.py` module should not be in the main branch, as these are unfinished experimental efforts to leverage the notion of surprisal to remove batch effects while retaining biological variation (this is also why you can't find documentation on these functions). As currently implemented, SCA does not perform batch correction, only dimensionality reduction, via `reduce` and `reduce_scanpy`.
